/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_absurd_packageupdata_PackageUpdata */

#ifndef _Included_com_absurd_packageupdata_PackageUpdata
#define _Included_com_absurd_packageupdata_PackageUpdata
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_absurd_packageupdata_PackageUpdata
 * Method:    patch
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_absurd_packageupdata_PackageUpdata_patch
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
